alias gch='git checkout'
alias gcht='git checkout --track -b'
alias gl='git log'
alias gls='git log --stat'
alias gst='git status'
alias gp='git pull -r'
alias gb='git branch'
alias gd='git diff'

alias mvi='mvn clean install -DskipTests' 
alias pylint='pylint --rcfile=~/.pylintrc'
